### ISSUE TITLE
Database Created

### ISSUE THREAD

**Issue by FearneT** [Caesiium/Skittles#16]
Database created in postgres
Notes: changed from the planned MySQL to PSQL for ease of use and integration with the app at present
Follow similar plan and made adjustments to table contents and structure to account for app usage

**Comment by FearneT** [comment]
![Image](https://github.com/user-attachments/assets/4d602a37-4c85-4c3e-bd7c-3e2ce5c147a9)

database plan and relations

**Comment by Caesiium** [comment]
Designed and planned out the format of the database, taking into account the multiple users who will all be able to access the same order. To ensure each user can add their own items and only be charged for those items each user has an entry in the users_in_order database to keep track of who has contributed to which order. Furthermore the table items_in_order adds an item per user, tracking the price and quantity to allow us to later query the table by user and calculate each users total cost.

**Comment by jakub2074** [comment]
Made initial database plan that Lydia built off of, and implemented her adjusted plan. Transferred the database from MySQL to PostgreSQL for improved concurrency and to enable use of more data types. Made relevant changes, e.g. made all 'id' columns serial primary keys to allow for automatic identification of supermarkets, groceries, users, orders, users in orders and items in orders, improving ease of use.
